"""Versioning details."""

__title__ = "nmbrs-database"
__version__ = "0.0.001"
__author__ = "Lars Kluijtmans"
__author_email__ = "info@lk-software.com"
__maintainer__ = "Lars Kluijtmans"
__maintainer_email__ = "info@lk-software.com"
__description__ = "Python SDK for the Visma Nmbrs SOAP API."
__license__ = "Lars Kluijtmans"
