"""This module provides access to all the employee level microservices."""

from .absence import EmployeeAbsenceService
from .address import EmployeeAddressService
from .bank_account import EmployeeBankAccountService
from .child import EmployeeChildService
from .contract import EmployeeContractService
from .cost_center import EmployeeCostCenterService
from .days import EmployeeDaysService
from .department import EmployeeDepartmentsService
from .document import EmployeeDocumentService
from .employment import EmployeeEmploymentService
from .function import EmployeeFunctionService
from .hour_component import EmployeeHourComponentFixedService
from .labour_agreement import EmployeeLabourAgreementService
from .lease_car import EmployeeLeaseCarService
from .leave import EmployeeLeaveService
from .levensloop import EmployeeLevensLoopService
from .manager import EmployeeManagerService
from .partner import EmployeePartnerService
from .personal_info import EmployeePersonalInfoService
from .salary import EmployeeSalaryService
from .schedule import EmployeeScheduleService
from .service import EmployeeServiceService
from .spaarloon import EmployeeSpaarloonService
from .svw import EmployeeSvwService
from .time_registration import EmployeeTimeRegistrationService
from .time_schedule import EmployeeTimeScheduleService
from .wage_component import EmployeeWageComponentsService
from .wage_tax import EmployeeWageTaxService
